
#Global Variables
SCENARIO_ROWS = 10      
SCENARIO_COLUMNS = 10
SCENARIO_TOPOLOGIES_NO = 200
SCENARIOS_NO = 10
TOPOLOGIES_TRAINING = 128
TOPOLOGIES_VALIDATION = 32
TOPOLOGIES_TESTING = 40
SCENARIOS_TRAINING = [1,2,4,6,7,10]
SCENARIOS_VALIDATION = [5,9]
SCENARIOS_TEST = [3,8]
DIVISION_BY_TOPOLOGIES = 1