
#Global Variables
SCENARIO_ROWS = 10      
SCENARIO_COLUMNS = 10
SCENARIO_TOPOLOGIES_NO = 200
SCENARIOS_NO = 10
TOPOLOGIES_TRAINING = 128
TOPOLOGIES_VALIDATION = 32
TOPOLOGIES_TESTING = 40
SCENARIOS_TRAINING = 6
SCENARIOS_VALIDATION = 2
SCENARIOS_TRAINING = 2
DIVISION_BY_TOPOLOGIES = 1